version: "3.9"

services:

  nginx:
    image: "nginx"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  php:
    build: .
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    healthcheck:
      test: curl --fail http://nginx/index.php | grep works || exit 1
      interval: 1s
      timeout: 3s
      retries: 3

